name = "nullsec-server"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "nsec.chames.dev", custom_domain = true }
]

# Cloudflare D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "nullsec-db"
database_id = "57838102-f104-4ab2-bc1a-684ee557de00"

[observability]
enabled = true
